/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controllers.CustomerController;
import Models.Customer;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Michail Sitmalidis
 */
public class SearchFrame extends javax.swing.JFrame {

    private MainFrame mainFrame;

    /**
     * Creates new form SearchFrame
     *
     */
    public SearchFrame(MainFrame mainFrame) {
        initComponents();
        this.mainFrame = mainFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1730, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 82, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jScrollPane2.setAlignmentX(0.0F);
        jScrollPane2.setAlignmentY(0.0F);
        jScrollPane2.setAutoscrolls(true);

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "customer_id", "first_name"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1713, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 17, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked


    }//GEN-LAST:event_jTable1MouseClicked

    public void CustomersList() {

        CustomerController customerController = new CustomerController();
        ArrayList<Customer> customers = customerController.populateCustomersTable();
        DefaultTableModel model = new DefaultTableModel();

        Object[] columnsName = new Object[11];

        columnsName[0] = "Id";
        columnsName[1] = "ΟΝΟΜΑ";
        columnsName[2] = "ΕΠΙΘΕΤΟ";
        columnsName[3] = "ΣΤΑΘΕΡΟ ΤΗΛΕΦΩΝΟ";
        columnsName[4] = "ΚΙΝΗΤΟ ΤΗΛΕΦΩΝΟ";
        columnsName[5] = "ΟΔΟΣ";
        columnsName[6] = "ΠΕΡΙΟΧΗ";
        columnsName[7] = "ΟΡΟΦΟΣ";
        columnsName[8] = "Τ.Κ.";
        columnsName[9] = "ΟΝΟΜΑ ΣΤΟ ΚΟΥΔΟΥΝΙ";
        columnsName[10] = "ΣΗΜΕΙΩΣΕΙΣ";
        model.setColumnIdentifiers(columnsName);
        Object[] tableRow = new Object[11];
        for (int i = 0; i < customers.size(); i++) {

            tableRow[0] = customers.get(i).getCustomer_id();
            tableRow[1] = customers.get(i).getFirstName();
            tableRow[2] = customers.get(i).getLastName();
            tableRow[3] = customers.get(i).getLandlinePhone();
            tableRow[4] = customers.get(i).getMobilePhone();
            tableRow[5] = customers.get(i).getStreet();
            tableRow[6] = customers.get(i).getDistrict();
            tableRow[7] = customers.get(i).getFloor();
            tableRow[8] = customers.get(i).getPostalCode();
            tableRow[9] = customers.get(i).getNameOnBell();
            tableRow[10] = customers.get(i).getFirstName();

            model.addRow(tableRow);
        }
        jTable1.setRowHeight(50);

        //columnModel.getColumn(0).setPreferredWidth(50);
        jTable1.setModel(model);
        TableColumnModel columnModel = jTable1.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(10);
        columnModel.getColumn(1).setPreferredWidth(300);
        columnModel.getColumn(2).setPreferredWidth(200);
        columnModel.getColumn(3).setPreferredWidth(50);
        columnModel.getColumn(4).setPreferredWidth(50);
        columnModel.getColumn(5).setPreferredWidth(50);
        columnModel.getColumn(6).setPreferredWidth(50);
        columnModel.getColumn(7).setPreferredWidth(50);
        columnModel.getColumn(8).setPreferredWidth(50);

        columnModel.getColumn(9).setPreferredWidth(50);
        columnModel.getColumn(10).setPreferredWidth(50);

    }

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        int i = jTable1.getSelectedRow();
        //   System.out.println(i);
        TableModel tableModel = jTable1.getModel();
        Customer customer = new Customer();
        customer.setCustomer_id(Integer.parseInt(tableModel.getValueAt(i, 0).toString()));
        customer.setFirstName(tableModel.getValueAt(i, 1).toString());
        customer.setLastName(tableModel.getValueAt(i, 2).toString());
        customer.setLandlinePhone(tableModel.getValueAt(i, 3).toString());
        customer.setMobilePhone(tableModel.getValueAt(i, 4).toString());
        customer.setStreet(tableModel.getValueAt(i, 5).toString());
        customer.setDistrict(tableModel.getValueAt(i, 6).toString());
        customer.setFloor(tableModel.getValueAt(i, 7).toString());
        customer.setPostalCode(tableModel.getValueAt(i, 8).toString());
        customer.setNameOnBell(tableModel.getValueAt(i, 9).toString());

        mainFrame.bulubulu(customer);
        if (evt.getClickCount() == 2) {
            this.dispose();
        }
    }//GEN-LAST:event_jTable1MousePressed

    /**
     * @param args the command line arguments
     *
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
